### ISSUE TITLE
Doesn't work for new version

### ISSUE THREAD

**Issue by Rucchao** [neunhoef/ArangoDBStarter#11]
Since I don't want to use Docker so I have no docker installed.

but when I perform  **make local**

it says /bin/sh: 1: docker: not found..

**Comment by neunhoef** [comment]
Acknowledged. We are in the process of restructuring this. We will create a way to build without docker, probably tomorrow.
Note also that the official URL of the repo has changed to
  https://github.com/arangodb-helper/ArangoDBStarter

**Comment by neunhoef** [comment]
This has been fixed in the new repo. The `make local` target now checks for the existence of a `docker` executable. If this is not there, a local build using a golang installation is done. I close this issue here now.

**Comment by Rucchao** [comment]
Got it, thanks a lot !

**Comment by Rucchao** [comment]
@neunhoef   Hi, Max, I find this project also related to you. ^_^ https://github.com/arangodb/1mDocsPerSec

Could you please tell me how to set up the connection to the Cluster if I use nodejs driver or how do I know the number of connection in cluster for one query because I'd like to compute the throughput?

Thanks!

The following is my default setting:

var arangojs = require('arangojs');
let db = arangojs('http://Coodinator:8530');
