### ISSUE TITLE
+1 for Docker support

### ISSUE THREAD

**Issue by pmualaba** [neunhoef/ArangoDBStarter#3]
With the new built in swarm support in Docker 1.12+ this should be the defacto way to boot an ArangoDB cluster before turning to DC/OS, which is a very nice escalation path when things grow really really big...
So what I would like to suggest is creating some best practice example docker-compose.yml files for the most popular environments, such as nginx loadbalancer container, with a couple of node.js containers talking to a cluster of ArangoDB containers (configured as GraphQL server) etc...
These docker-compose.yml files can then easily be tweaked to the developers need...

**Comment by neunhoef** [comment]
Point taken. I agree, a docker-compose.yml using this arangodb starter project should be rather straightforward.

**Comment by neunhoef** [comment]
Some progress has been made, but it does not work yet. Automatic address discovery and port exposing does not work yet, since Docker gets in the way. A concept for persisting the data directories has to be invented. Stay tuned.

**Comment by pmualaba** [comment]
Great! I will stay tuned. Thanks for working on this!

**Comment by neunhoef** [comment]
See the new repository (to which the project was moved):
  https://github.com/arangodb-helper/ArangoDBStarter
docker is now fully supported.
