### ISSUE TITLE
Undefined: sort.Reverse

### ISSUE THREAD

**Issue by Rucchao** [neunhoef/ArangoDBStarter#4]
Hi, Max:
   
  When I try this script to install ArangoDB cluster,  I got error says 

**go:604: undefined: sort.Reverse,** 

I am new to go, I try to install go using apt-get command, but it still didn't work, I know sort function is from "import sort", but why here can not work, could you please give me a hand with this ? Thanks.

-- Jason

**Comment by neunhoef** [comment]
As far as I see sort.Reverse exists since at least go1.4.3. Please use a recent go and the error should be gone.
